project: physics-uncertainty-exps
method: grid
parameters:
  data_seed:
    values: [0, 1, 2, 3, 4]
  num_epochs:
    value: 5000
  model_type:
    values: ["NN", "SpNN", "NonseparableHNN", "HNN", "MixtureHNN"]
  system_type:
    values: ["ChainPendulum", "FrictionChainPendulum"] 
  num_bodies:
    values: [1, 2, 3]
program: flex-hnn.py
command:
  - ${env}
  - python3
  - ${program}
  - ${args}