project: physics-uncertainty-exps
method: grid
parameters:
  data_seed:
    values: [0, 1, 2, 3]
  num_epochs:
    value: 1000
  model_type:
    values: ["NN", "SecondOrderNN", "MechanicsNN", "SpNN", "NonseparableHNN", "HNN", "MixtureHNN"]
  system_type:
    values: ["FrictionChainPendulum", "FrictionSpringPendulum"]
  num_bodies:
    values: [1, 2, 3]
program: flex-hnn.py
command:
  - ${env}
  - python3
  - ${program}
  - ${args}