project: physics-uncertainty-exps
method: grid
parameters:
  seed:
    values: [0, 1, 2, 3]
  model_type:
    values: ["NODE", "CoupledNODE"]
  hidden_size:
    values: [128, 256]
  task:
    values: ["HopperFull-v0", "SwimmerFull-v0"]
  num_epochs:
    values: [256]
  subsample_ratio:
    values: [0.0625, 0.125, 0.25, 0.5, 1.0]
  train_seq_len:
    values: [5]
program: mujoco.py
command:
  - ${env}
  - python3
  - ${program}
  - ${args}